version: "3.8"

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - .:/var/www:delegated
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./var/nginx:/var/log/nginx
    links:
      - php

  php:
    build:
      context: ./tools/docker/php
    volumes:
      - .:/var/www:delegated

  db:
    image: mariadb:10.6-focal
    restart: unless-stopped
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: gipfcip
      MYSQL_PASSWORD: qSh5UpClI0j0h8PA
      MYSQL_DATABASE: gipsign
      TZ: America/Martinique
    volumes:
      - db-data:/var/lib/mysql

  # Dev tools
  maildev:
    image: maildev/maildev
    command: bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS
    ports:
      - 1080:80
    restart: unless-stopped

volumes:
  db-data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: "./.docker/mariadb"
